name: Send a webhook when receive a telegram message
on:
  telegram_bot:
    # note: you should set webhook first, see https://github.com/actionsflow/actionsflow/tree/main/packages/actionsflow-trigger-telegram_bot#options
    webhook: true
jobs:
  webhook:
    name: Send HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl '${{ secrets.WEBHOOK_URL }}' --data  'entry.870605213=1'

