name: Send a webhook when receive a telegram message
on:
  telegram_bot:
    event: text
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
jobs:
  webhook:
    name: Send HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request 
        run: curl  ${{ secrets.WEBHOOK_URL }}   --data  'entry.870605213=1'
